// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOVbFI4iwROAPLHgc5IJhEc4xVSbGqJiM',
    appId: '1:791859972992:web:aee8dca56dc1f033c3cf65',
    messagingSenderId: '791859972992',
    projectId: 'carex-490114',
    authDomain: 'carex-490114.firebaseapp.com',
    storageBucket: 'carex-490114.firebasestorage.app',
    measurementId: 'G-QC7BDLG2ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH5otujDmFEB7hIconT1zgLyXOylaMsqk',
    appId: '1:791859972992:android:939d8be05c5a536ac3cf65',
    messagingSenderId: '791859972992',
    projectId: 'carex-490114',
    storageBucket: 'carex-490114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz8JIEpobS9Vqj1OxsvRtuEqb6uHOT9x4',
    appId: '1:791859972992:ios:62f2190bc00282e8c3cf65',
    messagingSenderId: '791859972992',
    projectId: 'carex-490114',
    storageBucket: 'carex-490114.firebasestorage.app',
    iosBundleId: 'com.example.carex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz8JIEpobS9Vqj1OxsvRtuEqb6uHOT9x4',
    appId: '1:791859972992:ios:62f2190bc00282e8c3cf65',
    messagingSenderId: '791859972992',
    projectId: 'carex-490114',
    storageBucket: 'carex-490114.firebasestorage.app',
    iosBundleId: 'com.example.carex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOVbFI4iwROAPLHgc5IJhEc4xVSbGqJiM',
    appId: '1:791859972992:web:09b723d619580edcc3cf65',
    messagingSenderId: '791859972992',
    projectId: 'carex-490114',
    authDomain: 'carex-490114.firebaseapp.com',
    storageBucket: 'carex-490114.firebasestorage.app',
    measurementId: 'G-F2HNB3PFFK',
  );
}
